const photoSizes = [
	"Select One",
	"Stamp",
	"Passport",
	"DV",
	"3R",
	"4R",
	"5R",
	"6R",
	"8R",
	"10R",
	"10L",
];

export const inputs = [
	{
		id: "snapType",
		label: "Snap Type",
		options: ["Select One", "Snapshot", "Scan"],
		type: "select",
		isLab: false,
	},
	{
		id: "photoNo",
		label: "Photo No.",
		placeholder: "DC/",
		type: "text",
		isLab: false,
	},
	{
		id: "photoSizePrint",
		label: "Photo Size (Print)",
		options: photoSizes,
		type: "select",
		isLab: false,
	},
	{
		id: "quantity",
		label: "Quantity",
		placeholder: 0,
		type: "number",
		isLab: false,
	},
	{
		id: "amount",
		label: "Amount",
		placeholder: 0,
		type: "number",
		isLab: false,
	},
	{
		id: "printType",
		label: "Print Type",
		options: ["Select One", "Normal", "Lab"],
		type: "select",
		isLab: false,
	},
	{
		id: "deliveryType",
		label: "Delivery Type",
		options: ["Select One", "Non-Urgent", "Urgent"],
		type: "select",
		isLab: true,
	},
	{
		id: "photoSizeLab",
		label: "Photo Size (Lab)",
		options: photoSizes,
		type: "select",
		isLab: true,
	},
	{
		id: "labQuantity",
		label: "Lab Quantity",
		placeholder: 0,
		type: "number",
		isLab: true,
	},
];
